INSERT INTO POLICY (POLICY_ID, POLICY_NAME, POLICY_TYPE, PREMIUM_AMOUNT, COVERAGE_AMOUNT, NOMINEE_NAME, POLICY_STATUS) 
VALUES ('POL1001', 'Family Health Plus', 'Health Insurance', 15000.00, '500000', 'Rajesh Kumar', 'ACTIVE');

INSERT INTO POLICY (POLICY_ID, POLICY_NAME, POLICY_TYPE, PREMIUM_AMOUNT, COVERAGE_AMOUNT, NOMINEE_NAME, POLICY_STATUS) 
VALUES ('POL1002', 'Secure Life Pro', 'Life Insurance', 25000.00, '1000000', 'Sunita Sharma', 'ACTIVE');

INSERT INTO POLICY (POLICY_ID, POLICY_NAME, POLICY_TYPE, PREMIUM_AMOUNT, COVERAGE_AMOUNT, NOMINEE_NAME, POLICY_STATUS) 
VALUES ('POL1003', 'Auto Shield', 'Car Insurance', 12000.00, '300000', 'Amit Patel', 'ACTIVE');

INSERT INTO POLICY (POLICY_ID, POLICY_NAME, POLICY_TYPE, PREMIUM_AMOUNT, COVERAGE_AMOUNT, NOMINEE_NAME, POLICY_STATUS) 
VALUES ('POL1004', 'Home Safe', 'Home Insurance', 18000.00, '750000', 'Priya Singh', 'PENDING');

INSERT INTO POLICY (POLICY_ID, POLICY_NAME, POLICY_TYPE, PREMIUM_AMOUNT, COVERAGE_AMOUNT, NOMINEE_NAME, POLICY_STATUS) 
VALUES ('POL1005', 'Travel Guard', 'Travel Insurance', 5000.00, '200000', 'Michael John', 'ACTIVE');